import Head from 'next/head';

import { gql } from '@apollo/client';
import client from '../apollo-client';

import Layout from '../src/components/Layout';
import { Box } from '@mui/material';
import Project from '../src/components/Project';

export default function Home({ data }) {
  console.log('All Projects', data);
  return (
    <>
      <Head>
        <title>Aimee Tacchi Portfolio 2022</title>
        <meta name="description" content="Aimee Tacchi Portfolio Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Box sx={{ display: 'flex', gap: 3, flexWrap: 'wrap', marginLeft: '89px' }}>
          {data.map(project => (
            <Project key={project.id} project={project} />
          ))}
        </Box>
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
            query AllProjects {
                allProjects {
                    id
                    name
                    slug
                    description
                    excerpt
                    link
                    tech
                    recentWork
                    coverImage {
                        id
                        responsiveImage(imgixParams: { fit: crop, w: 300, h: 300, auto: format }) {
                            srcSet
                            webpSrcSet
                            sizes
                            src
                            width
                            height
                            aspectRatio
                            alt
                            title
                            base64
                        }
                    }
                }
            }
        `,
  });

  return {
    props: {
      data: data.allProjects,
    },
  };
}
